# Generated by Django 5.1.6 on 2025-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('normal', 'Normal')], default='normal', max_length=10)),
            ],
        ),
    ]
