# Generated by Django 3.2.9 on 2025-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecaFP',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100)),
                ('renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edad', models.PositiveIntegerField()),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
